Allow testing resources with multiple extensions (#32)
* Use Union instead of tuple for creating a Resource with multiple extension

Using a tuple results in a pydantic error:
  File "/usr/local/lib/python3.11/site-packages/pydantic/_internal/_generics.py", line 373, in map_generic_model_arguments
    raise TypeError(f'Too many arguments for {cls}; actual {len(args)}, expected {expected_len}')
TypeError: Too many arguments for <class 'scim2_models.rfc7643.schema.User'>; actual 3, expected 1

* Add unit test for discovering resource types with multiple extensions

* Fix check_resource_model if resource_models was created from schemas

* fix: pre-commit

* fix: unit tests

---------

Co-authored-by: Jan Burgmeier <jan@jb-eng.de>